### ISSUE TITLE
Choose a license?

### ISSUE THREAD

**Issue by ShaneCurcuru** [bostonopen/bostonopen.github.io#4]
MIT or Apache is what I recommend, personally.  Not sure I can make this month, but hoping to come in the future!

**Comment by pdurbin** [comment]
@ShaneCurcuru good idea. I don't feel strongly about which license but in 9e240d8 I added Apache because it's what we use at work. 🤷 

We're right now talking in Quiet about when to meet in May! If you shoot me an email at philipdurbin@gmail.com I can send you an invite code for Quiet.

**Comment by pdurbin** [comment]
There's a proposal to switch to AGPL:

- #14
